on:
  schedule:
    - cron: 0 5 * * 0-4 #UTC
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to run (optional)'
        required: false

env:
  GITHUB_RUN: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  BRANCH_NAME: ${{ github.head_ref || 'fff' }}
