on:
  schedule:
    - cron: 50 * * * *
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to run (optional)'
        required: false

env:
  GITHUB_RUN: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  BRANCH_NAME: ${{ github.head_ref || 'fff' }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
