on:
  schedule:
    - cron: 20 * * * *
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to run (optional)'
        required: false

env:
  GITHUB_RUN: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
      with:
        ref: fff

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        gulp
